// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: proto/directory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmpDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeptId    int32  `protobuf:"varint,3,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	ManagerId int32  `protobuf:"varint,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
}

func (x *EmpDetails) Reset() {
	*x = EmpDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmpDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpDetails) ProtoMessage() {}

func (x *EmpDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpDetails.ProtoReflect.Descriptor instead.
func (*EmpDetails) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{0}
}

func (x *EmpDetails) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmpDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmpDetails) GetDeptId() int32 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *EmpDetails) GetManagerId() int32 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

type EmpList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeptName    string `protobuf:"bytes,2,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	ManagerName string `protobuf:"bytes,3,opt,name=manager_name,json=managerName,proto3" json:"manager_name,omitempty"`
}

func (x *EmpList) Reset() {
	*x = EmpList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmpList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpList) ProtoMessage() {}

func (x *EmpList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpList.ProtoReflect.Descriptor instead.
func (*EmpList) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{1}
}

func (x *EmpList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmpList) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *EmpList) GetManagerName() string {
	if x != nil {
		return x.ManagerName
	}
	return ""
}

type CreateEmpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E *EmpDetails `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *CreateEmpRequest) Reset() {
	*x = CreateEmpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmpRequest) ProtoMessage() {}

func (x *CreateEmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmpRequest.ProtoReflect.Descriptor instead.
func (*CreateEmpRequest) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEmpRequest) GetE() *EmpDetails {
	if x != nil {
		return x.E
	}
	return nil
}

type CreateEmpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E *EmpDetails `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *CreateEmpResponse) Reset() {
	*x = CreateEmpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmpResponse) ProtoMessage() {}

func (x *CreateEmpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmpResponse.ProtoReflect.Descriptor instead.
func (*CreateEmpResponse) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEmpResponse) GetE() *EmpDetails {
	if x != nil {
		return x.E
	}
	return nil
}

type ReadEmpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadEmpRequest) Reset() {
	*x = ReadEmpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEmpRequest) ProtoMessage() {}

func (x *ReadEmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEmpRequest.ProtoReflect.Descriptor instead.
func (*ReadEmpRequest) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{4}
}

type ReadEmpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	El []*EmpList `protobuf:"bytes,1,rep,name=el,proto3" json:"el,omitempty"`
}

func (x *ReadEmpResponse) Reset() {
	*x = ReadEmpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEmpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEmpResponse) ProtoMessage() {}

func (x *ReadEmpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEmpResponse.ProtoReflect.Descriptor instead.
func (*ReadEmpResponse) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{5}
}

func (x *ReadEmpResponse) GetEl() []*EmpList {
	if x != nil {
		return x.El
	}
	return nil
}

type UpdateEmpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateEmpRequest) Reset() {
	*x = UpdateEmpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmpRequest) ProtoMessage() {}

func (x *UpdateEmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmpRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmpRequest) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEmpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateEmpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateEmpResponse) Reset() {
	*x = UpdateEmpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEmpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmpResponse) ProtoMessage() {}

func (x *UpdateEmpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmpResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmpResponse) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEmpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteEmpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteEmpRequest) Reset() {
	*x = DeleteEmpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmpRequest) ProtoMessage() {}

func (x *DeleteEmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmpRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmpRequest) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEmpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteEmpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteEmpResponse) Reset() {
	*x = DeleteEmpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_directory_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmpResponse) ProtoMessage() {}

func (x *DeleteEmpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_directory_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmpResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmpResponse) Descriptor() ([]byte, []int) {
	return file_proto_directory_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEmpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_directory_proto protoreflect.FileDescriptor

var file_proto_directory_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x70,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x65, 0x70, 0x74,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x5d, 0x0a, 0x07, 0x45, 0x6d, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x2d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x01, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x45, 0x6d, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x01, 0x65, 0x22,
	0x2e, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x01, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x45, 0x6d, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x01, 0x65, 0x22,
	0x10, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x2b, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x02, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x45, 0x6d, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x02, 0x65, 0x6c, 0x22, 0x26,
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45,
	0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xe2, 0x01, 0x0a,
	0x0a, 0x45, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x73,
	0x61, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x12, 0x11, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x73, 0x61, 0x79, 0x52, 0x65, 0x61, 0x64, 0x45, 0x6d, 0x70,
	0x12, 0x0f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x73, 0x61, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6d, 0x70, 0x12, 0x11, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x73, 0x61,
	0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x12, 0x11, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_directory_proto_rawDescOnce sync.Once
	file_proto_directory_proto_rawDescData = file_proto_directory_proto_rawDesc
)

func file_proto_directory_proto_rawDescGZIP() []byte {
	file_proto_directory_proto_rawDescOnce.Do(func() {
		file_proto_directory_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_directory_proto_rawDescData)
	})
	return file_proto_directory_proto_rawDescData
}

var file_proto_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_directory_proto_goTypes = []interface{}{
	(*EmpDetails)(nil),        // 0: EmpDetails
	(*EmpList)(nil),           // 1: EmpList
	(*CreateEmpRequest)(nil),  // 2: CreateEmpRequest
	(*CreateEmpResponse)(nil), // 3: CreateEmpResponse
	(*ReadEmpRequest)(nil),    // 4: ReadEmpRequest
	(*ReadEmpResponse)(nil),   // 5: ReadEmpResponse
	(*UpdateEmpRequest)(nil),  // 6: UpdateEmpRequest
	(*UpdateEmpResponse)(nil), // 7: UpdateEmpResponse
	(*DeleteEmpRequest)(nil),  // 8: DeleteEmpRequest
	(*DeleteEmpResponse)(nil), // 9: DeleteEmpResponse
}
var file_proto_directory_proto_depIdxs = []int32{
	0, // 0: CreateEmpRequest.e:type_name -> EmpDetails
	0, // 1: CreateEmpResponse.e:type_name -> EmpDetails
	1, // 2: ReadEmpResponse.el:type_name -> EmpList
	2, // 3: EmpService.sayCreateEmp:input_type -> CreateEmpRequest
	4, // 4: EmpService.sayReadEmp:input_type -> ReadEmpRequest
	6, // 5: EmpService.sayUpdateEmp:input_type -> UpdateEmpRequest
	8, // 6: EmpService.sayDeleteEmp:input_type -> DeleteEmpRequest
	3, // 7: EmpService.sayCreateEmp:output_type -> CreateEmpResponse
	5, // 8: EmpService.sayReadEmp:output_type -> ReadEmpResponse
	7, // 9: EmpService.sayUpdateEmp:output_type -> UpdateEmpResponse
	9, // 10: EmpService.sayDeleteEmp:output_type -> DeleteEmpResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_directory_proto_init() }
func file_proto_directory_proto_init() {
	if File_proto_directory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_directory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmpDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmpList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEmpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEmpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEmpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEmpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_directory_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_directory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_directory_proto_goTypes,
		DependencyIndexes: file_proto_directory_proto_depIdxs,
		MessageInfos:      file_proto_directory_proto_msgTypes,
	}.Build()
	File_proto_directory_proto = out.File
	file_proto_directory_proto_rawDesc = nil
	file_proto_directory_proto_goTypes = nil
	file_proto_directory_proto_depIdxs = nil
}
